#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Update /etc/hosts to set localhost to 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Update /etc/hosts to set facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
